interface CollectionInfo {
    schema: unknown;
}

export function generateTypes(
    collections: Record<string, CollectionInfo>,
    configPath: string,
    componentType: string,
): string {
    let collectionEntries = Object.entries(collections);

    let entryMapEntries = collectionEntries
        .map(([name]) => {
            return `		${name}: {
			[id: string]: import("@withsprinkles/content-layer").DataEntry<
				_InferSchemaOutput<_ResolveSchema<_Collections["${name}"]["schema"]>>
			> & {
				collection: "${name}";
			};
		};`;
        })
        .join("\n");

    return `// Auto-generated by @withsprinkles/content-layer
// Do not edit this file manually

declare module "sprinkles:content" {
	type _Collections = typeof import("${configPath}").collections;
	type _ResolveSchema<T> = T extends (...args: any[]) => infer R ? R : T;
	type _InferSchemaOutput<S> = S extends { "~standard": { types?: infer T } }
		? T extends { output: infer O }
			? O
			: never
		: never;

	interface ContentEntryMap {
${entryMapEntries}
	}

	type Flatten<T> = T extends { [K: string]: infer U } ? U : never;
	type CollectionKey = keyof ContentEntryMap;
	type CollectionEntry<C extends CollectionKey> = Flatten<ContentEntryMap[C]>;

	type ReferenceContentEntry<
		C extends keyof ContentEntryMap,
		E extends ContentEntryMap[C] | (string & {}) = string,
	> = {
		collection: C;
		id: E;
	};

	export function getCollection<C extends CollectionKey>(
		collection: C,
		filter?: (entry: CollectionEntry<C>) => unknown,
	): Promise<CollectionEntry<C>[]>;

	export function getEntry<C extends CollectionKey>(
		collection: C,
		slug: string,
	): Promise<CollectionEntry<C> | undefined>;

	export function getEntry<C extends CollectionKey>(
		entry: ReferenceContentEntry<C>,
	): Promise<CollectionEntry<C> | undefined>;

	export function getEntries<C extends CollectionKey>(
		entries: ReferenceContentEntry<C>[],
	): Promise<CollectionEntry<C>[]>;

	export function render<C extends CollectionKey>(
		entry: CollectionEntry<C>,
	): Promise<{ Content: ${componentType}; headings: import("@withsprinkles/content-layer").MarkdownHeading[] }>;

	export function defineCollection<
		S extends
			| import("@withsprinkles/content-layer").StandardSchemaV1<any, any>
			| ((
					ctx: import("@withsprinkles/content-layer").SchemaContext,
				) => import("@withsprinkles/content-layer").StandardSchemaV1<any, any>),
	>(
		input: { loader: import("@withsprinkles/content-layer").ContentLoader; schema: S },
	): { loader: import("@withsprinkles/content-layer").ContentLoader; schema: S };

	export function reference<C extends string>(
		collection: C,
	): import("@withsprinkles/content-layer").ReferenceSchema<C>;
}
`;
}
