/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false`
declare namespace Cloudflare {
    interface Env {
        ASSETS: Fetcher;
    }
}
interface Env extends Cloudflare.Env {}
